---
- name: Set Tomcat Download URL
  set_fact:
    # tomcat_download_url: "https://downloads.apache.org/tomcat/tomcat-{{ tomcat_main_version }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    tomcat_download_url: "https://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_main_version }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"

- name: Update apt repository cache
  apt:
    update_cache: yes

- name: Ensure the necessary packages are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "openjdk-{{ java_version }}-jdk"
    - wget
    - curl

- name: Create Tomcat installation directory
  file:
    path: "{{ tomcat_install_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: Download Tomcat
  get_url:
    url: "{{ tomcat_download_url }}"
    dest: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    mode: '0644'

- name: Extract Tomcat
  unarchive:
    src: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_dir }}"
    remote_src: yes

- name: Set permissions on Tomcat directory
  file:
    path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
    recurse: yes

- name: Set JAVA_HOME in .bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")'
    state: present
  become: true
  become_user: "{{ user }}"

- name: Delete all files in the Tomcat webapps directory
  file:
    path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/webapps"
    state: absent

- name: Recreate the webapps directory after deletion
  file:
    path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/webapps"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0750'    

- name: Create systemd service file for tomcat
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Enable and stop tomcat service
  systemd:
    name: tomcat
    enabled: true
    state: stopped